---

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.0.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml

- repo: https://github.com/ansible/ansible-lint.git
  rev: v3.5.1
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
