---

language: generic
python: "2.7"

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: ANSIBLE_VERSION=2.7.4.0

# Install Ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install Ansible with pip
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo pip install ansible==${ANSIBLE_VERSION}; fi

  # Check Ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\n' > ansible.cfg

  # Configure ansible.cfg on Linux
  - >
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      printf '\n[privilege_escalation]\nbecome=True' >> ansible.cfg
    fi

script:

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test role run
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Test idempotence
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - command -v hyper
