---
# tasks file for markosamuli.hyper

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}_{{ ansible_architecture }}.yml"
      - "default.yml"
      paths: vars

- include: Debian.yml
  when: ansible_os_family == 'Debian'
