---
- name: Create temporary download directory
  tempfile:
    state: directory
    suffix: hyper
  register: hyper_tmp

- name: Download Hyper .rpm package
  get_url:
    url: "{{ hyper_rhel_url }}"
    dest: "{{ hyper_tmp.path }}/{{ hyper_rhel_file }}"
    checksum: "{{ hyper_rhel_checksum }}"

- name: Install Hyper .rpm package
  dnf:
    name: "{{ hyper_tmp.path }}/{{ hyper_rhel_file }}"
    state: present

- name: Cleanup temp directory
  file:
    path: "{{ hyper_tmp.path }}"
    state: absent
